image: denoland/deno:2.0.5

default:
  interruptible: true

stages:
  - compile

compile:
  stage: compile
  script:
    - deno fmt --check
    - deno lint
    - deno task test
    - deno compile -A -o knox-x86_64-unknown-linux-gnu --target x86_64-unknown-linux-gnu src/main.ts
    - deno compile -A -o knox-aarch64-unknown-linux-gnu --target aarch64-unknown-linux-gnu src/main.ts
    - deno compile -A -o knox-x86_64-pc-windows-msvc.exe --target x86_64-pc-windows-msvc src/main.ts
    - deno compile -A -o knox-x86_64-apple-darwin --target x86_64-apple-darwin src/main.ts
    - deno compile -A -o knox-aarch64-apple-darwin --target aarch64-apple-darwin src/main.ts
  artifacts:
    when: always
    paths:
      - knox-x86_64-unknown-linux-gnu
      - knox-aarch64-unknown-linux-gnu
      - knox-x86_64-pc-windows-msvc.exe
      - knox-x86_64-apple-darwin
      - knox-aarch64-apple-darwin
