image: denoland/deno:2.0.5

default:
  interruptible: true

stages:
  - compile

compile:
  stage: compile
  script:
    - deno fmt --check
    - deno lint
    - deno task test
    - deno task compile --target x86_64-unknown-linux-gnu
    - deno task compile --target aarch64-unknown-linux-gnu
    - deno task compile --target x86_64-pc-windows-msvc
    - deno task compile --target x86_64-apple-darwin
    - deno task compile --target aarch64-apple-darwin
  artifacts:
    when: always
    paths:
      - knox-x86_64-unknown-linux-gnu
      - knox-aarch64-unknown-linux-gnu
      - knox-x86_64-pc-windows-msvc.exe
      - knox-x86_64-apple-darwin
      - knox-aarch64-apple-darwin
