image: denoland/deno:2.0.4

default:
  interruptible: true

stages:
  - compile

compile:
  stage: compile
  script:
    - deno fmt --check
    - deno lint
    - deno task test
    - deno task compile
  artifacts:
    when: always
    paths:
      - knox
